robot_cfg:
  kinematics:
    usd_path: "robot/piper_description/piper.usd"
    usd_robot_root: "/robot"
    isaac_usd_path: ""
    usd_flip_joints: {}
    usd_flip_joint_limits: []

    urdf_path: "robot/piper_description/piper_description.urdf"
    asset_root_path: "robot/piper_description"
    
    base_link: "base_link"
    ee_link: "gripper_base"
    link_names: null
    lock_joints: null              #{"joint7": 0.0}
    extra_links: null

    
    collision_link_names: 
      [
        'link1',
        'link2', 
        'link3', 
        'link4', 
        'link5',
        'link6', 
        "gripper_base",
        'link7',
        'link8'
      ] # List[str]
    collision_spheres: "spheres/piper.yml"
    collision_sphere_buffer: 0.0
    extra_collision_spheres: {}
    self_collision_ignore: 
    {
      "link1": ["base_link","link2"],
      "link2": ["link1", "link3"],
      "link3": ["link2", "link4"],
      "link4": ["link3","link5"],
      "link5": ["link4", "link6"],
      "link6": ["link7","link5"],
    }
    self_collision_buffer: {} 
      
    use_global_cumul: True
    mesh_link_names: 
    [
      'link1',
      'link2',
      'link3',
      'link4', 
      'link5',
      'link6'
    ]  # List[str]
    external_asset_path: null # Use this to add path for externally located assets/robot folder.

    cspace:
      joint_names: ['joint1','joint2', 'joint3','joint4' ,'joint5', 'joint6'
      ]
      retract_config:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      null_space_weight:  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_jerk: 500.0
      max_acceleration: 12.0
      position_limit_clip: 0.1
      
      
      