# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0

# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# Lula will only use these joints to control the robot position.
cspace:
    - right_arm_joint1
    - right_arm_joint2
    - right_arm_joint3
    - right_arm_joint4
    - right_arm_joint5
    - right_arm_joint6
    - right_arm_joint7

default_q: [
    1.8733,-1.339,-2.694,0.8368,-1.0589,-0.7835,1.2693, ## for replay
    ]

acceleration_limits: [
   10,10,10,10,10,10,10
]

jerk_limits: [
   10000,10000,10000,10000,10000,10000,10000
]

# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted or how values in the URDF should be overwritten.
# for replay
cspace_to_urdf_rules:
    - {name: joint_lift_body, rule: fixed, value: 0.1995}
    - {name: joint_body_pitch, rule: fixed, value: 0.6025}
    - {name: joint_head_yaw, rule: fixed, value: 0.0}
    - {name: joint_head_pitch, rule: fixed, value: 0.6708}
    - {name: left_arm_joint1, rule: fixed, value: -1.0817}
    - {name: left_arm_joint2, rule: fixed, value: 0.5907}
    - {name: left_arm_joint3, rule: fixed, value: 0.3442}
    - {name: left_arm_joint4, rule: fixed, value: -1.2819}
    - {name: left_arm_joint5, rule: fixed, value: 0.6928}
    - {name: left_arm_joint6, rule: fixed, value: 1.4725}
    - {name: left_arm_joint7, rule: fixed, value: -0.1599}



# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
