##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    usd_flip_joints: {}
    usd_flip_joint_limits: []

    urdf_path: "robot/galbot_one_charlie.urdf"
    asset_root_path: ""

    base_link: "base_link"
    ee_link: "right_suction_cup_tcp_link"
    link_names: ["base_link", "omni_chassis_base_link",
    "leg_link1", "leg_link2", "leg_link3", "leg_link4", "head_base_link", "head_link1", "head_link2", "left_arm_base_link", "left_arm_link1", "left_arm_link2", "left_arm_link3", "left_arm_link4", "left_arm_link5", "left_arm_link6", "left_arm_link7", "left_gripper_base_link", "left_gripper_left_link", "left_gripper_right_link", "left_gripper_tcp_link"]

    lock_joints: {
      "leg_joint1": 0.8,
      "leg_joint2": 2.3,
      "leg_joint3": 1.85,
      "leg_joint4": 0.0,
      "head_joint1": 0.0,
      "left_arm_joint1": 2.10,
      "head_joint2": 0.36,
      "left_arm_joint2": -1.45,
      "left_arm_joint3": 0.05,
      "left_arm_joint4": 1.57,
      "left_arm_joint5": -1.57,
      "left_arm_joint6": 0.0,
      "left_arm_joint7": -0.74,
      "left_gripper_left_joint": 0.0,
      "left_gripper_right_joint": 0.0,
      "right_suction_cup_joint1": 0.0
      }
    extra_links: null


    collision_link_names: ["right_arm_link1", "right_arm_link2", "right_arm_link3", "right_arm_link4", "right_arm_link5", "right_arm_link6", "right_arm_link7", "right_suction_cup_base_link", "right_suction_cup_link1"] # List[str]
    collision_spheres:
      right_arm_link1:
        - "center": [-0.0, -0.0, -0.009]
          "radius": 0.07
        - "center": [-0.0, -0.0, -0.06]
          "radius": 0.05
      right_arm_link2:
        - "center": [-0.0, -0.149, -0.0]
          "radius": 0.06
        - "center": [-0.0, -0.083, -0.0]
          "radius": 0.06
        - "center": [-0.0, -0.02, -0.0]
          "radius": 0.08
      right_arm_link3:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.06
        - "center": [0.0, -0.0, -0.138]
          "radius": 0.05
        - "center": [0.0, -0.0, -0.049]
          "radius": 0.05646
        - "center": [0.0, -0.0, -0.095]
          "radius": 0.05313
      right_arm_link4:
        - "center": [0.0, -0.078, -0.0]
          "radius": 0.06
        - "center": [0.0, -0.017, -0.0]
          "radius": 0.07
      right_arm_link5:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.06
        - "center": [-0.0, 0.0, -0.192]
          "radius": 0.06
        - "center": [-0.0, 0.0, -0.067]
          "radius": 0.06649
        - "center": [-0.0, 0.0, -0.131]
          "radius": 0.06316
      right_arm_link6:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.06
      right_arm_link7:
        - "center": [-0.054, -0.0, 0.0]
          "radius": 0.05
        - "center": [-0.058, 0.052, -0.002]
          "radius": 0.06
        - "center": [-0.007, 0.0, -0.064]
          "radius": 0.035
      right_suction_cup_base_link:
        - "center": [-0.028, -0.0, 0.0]
          "radius": 0.05
        - "center": [-0.08, -0.0, 0.0]
          "radius": 0.02
        - "center": [-0.137, -0.0, 0.0]
          "radius": 0.02
        - "center": [-0.099, -0.0, 0.0]
          "radius": 0.02
        - "center": [-0.118, -0.0, 0.0]
          "radius": 0.02
      right_suction_cup_link1:
        - "center": [0.0, -0.017, 0.0]
          "radius": 0.02
        - "center": [0.0, -0.035, 0.0]
          "radius": 0.02
        - "center": [0.0, -0.057, 0.0]
          "radius": 0.02
        - "center": [0.0, -0.073, 0.0]
          "radius": 0.025

    collision_sphere_buffer: 0.0 # float or Dict[str, float]
    extra_collision_spheres: {}
    self_collision_ignore: {
      "right_arm_link1": ["right_arm_link2"],
      "right_arm_link2": ["right_arm_link3"],
      "right_arm_link3": ["right_arm_link4", "right_arm_link5","right_arm_link6", "right_arm_link7"],
      "right_arm_link4": ["right_arm_link5", "right_arm_link6","right_arm_link7"],
      "right_arm_link5": ["right_arm_link6", "right_arm_link7"],
      "right_arm_link6": ["right_arm_link7", "right_suction_cup_link1", "right_suction_cup_base_link"],
      "right_arm_link7": ["right_suction_cup_link1", "right_arm_link5"],
      "right_suction_cup_base_link": ["right_suction_cup_link1", "right_arm_link7"],
    } # Dict[str, List[str]]
    self_collision_buffer: {
      "right_arm_link1": 0,
      "right_arm_link2": 0,
      "right_arm_link3": 0,
      "right_arm_link4": 0,
      "right_arm_link5": 0,
      "right_arm_link6": 0,
      "right_arm_link7": 0,
      "right_suction_cup_base_link": 0,
    } # Dict[str, float]

    use_global_cumul: True
    mesh_link_names: null # List[str]
    external_asset_path: null # Use this to add path for externally located assets/robot folder.

    cspace:
      joint_names: ['right_arm_joint1','right_arm_joint2', 'right_arm_joint3', 'right_arm_joint4', 'right_arm_joint5', 'right_arm_joint6', 'right_arm_joint7']
 # List[str]
      retract_config: [1.25, 0.8, -1, 1.57, 0, -0.74, 0] # List[float]
      null_space_weight:  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # List[str]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # List[str]
      max_jerk: 500.0
      max_acceleration: 15.0
