# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0

# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# Lula will only use these joints to control the robot position.
cspace:
    - left_arm_joint1
    - left_arm_joint2
    - left_arm_joint3
    - left_arm_joint4
    - left_arm_joint5
    - left_arm_joint6
    - left_arm_joint7


## init semi-stand grasp pose
default_q: [-0.5480, -0.6551, 2.407, 1.3641, -0.4416, -0.1476, 1.2308]


#id: 6,9,11,13,15,17,19
acceleration_limits: [
   10,10,10,10,10,10,10
]

jerk_limits: [
   10000,10000,10000,10000,10000,10000,10000
]

# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted or how values in the URDF should be overwritten.

## init stand pose provided by Galbot
cspace_to_urdf_rules:
## semi-stand pose
# 4 leg degree: [20,80,60,0] rad: [0.349, 1.396, 1.047, 0]

# cspace_to_urdf_rules:
    # - {name: leg_joint1, rule: fixed, value: 0.349}
    # - {name: leg_joint2, rule: fixed, value: 1.396}
    # - {name: leg_joint3, rule: fixed, value: 1.3}
    - {name: leg_joint1, rule: fixed, value: 0.8}
    - {name: leg_joint2, rule: fixed, value: 2.3}
    - {name: leg_joint3, rule: fixed, value: 1.55}
    - {name: leg_joint4, rule: fixed, value: 0.0}
    - {name: head_joint1, rule: fixed, value: -0.12}
    - {name: right_arm_joint1, rule: fixed, value: 0.5480}
    - {name: head_joint2, rule: fixed, value: 0.36}
    - {name: right_arm_joint2, rule: fixed, value: 0.6551}
    - {name: right_arm_joint3, rule: fixed, value: 0.7330}
    - {name: right_arm_joint4, rule: fixed, value: 1.3641}
    - {name: right_arm_joint5, rule: fixed, value: 0.4416}
    - {name: right_arm_joint6, rule: fixed, value: 0.1476}
    - {name: right_arm_joint7, rule: fixed, value: 1.2308}
    - {name: left_gripper_left_joint, rule: fixed, value: 0.0}
    - {name: left_gripper_right_joint, rule: fixed, value: 0.0}
    - {name: right_suction_cup_joint1, rule: fixed, value: 0.0}


# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
