 link1:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.0045
      link2:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.005
        - "center": [0.287, -0.013, -0.0]
          "radius": 0.005
        - "center": [0.048, -0.002, -0.0]
          "radius": 0.005
        - "center": [0.096, -0.004, -0.0]
          "radius": 0.005
        - "center": [0.144, -0.007, -0.0]
          "radius": 0.005
        - "center": [0.192, -0.009, -0.0]
          "radius": 0.005
        - "center": [0.24, -0.011, -0.0]
          "radius": 0.005

      link3:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.0045
        - "center": [-0.017, -0.182, 0.0]
          "radius": 0.004
        - "center": [-0.004, -0.047, 0.0]
          "radius": 0.00437
        - "center": [-0.009, -0.094, 0.0]
          "radius": 0.00424
        - "center": [-0.013, -0.138, 0.0]
          "radius": 0.00412
      link4:
         - "center": [0.0, 0.0, 0.0]
           "radius": 0.004
      link5: 
        - "center": [0.006, -0.058, 0.0]
          "radius": 0.0045
      link6: 
        - "center": [0.003, 0.0, 0.026]
          "radius": 0.005
      link7:
        - "center": [0.001, 0.001, 0.001]
          "radius": 0.005 #0.05